// ==UserScript==
// @name         Xynigo SHEIN 店铺接码助手
// @namespace    https://github.com/wrangler1024/crossborder-userscripts
// @version      0.1.1
// @description  SHEIN 登录发码后自动轮询店铺接码链接并填入验证码，确认登录仍由运营人员手动完成。
// @author       Samforo
// @homepageURL  https://github.com/wrangler1024/crossborder-userscripts/tree/main/scripts/shein-store-otp-assistant
// @supportURL   https://github.com/wrangler1024/crossborder-userscripts/issues
// @match        https://sellerhub.shein.com/*
// @icon         https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/assets/xynigo-mascot.png
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// @grant        GM_xmlhttpRequest
// @connect      api.68sms.com
// @run-at       document-start
// @noframes
// @downloadURL  https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/scripts/shein-store-otp-assistant/xynigo_shein_store_otp_assistant.user.js
// @updateURL    https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/scripts/shein-store-otp-assistant/xynigo_shein_store_otp_assistant.user.js
// ==/UserScript==

// Generated from the shared Manifest V3 source. Do not edit this file by hand.
'use strict';

(function exposeXynigoSheinOtpUserscriptRuntime(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.XynigoSheinOtpUserscriptRuntime = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createUserscriptRuntime() {
  'use strict';

  const SETTINGS_KEY = 'sheinOtpAssistantSettings';
  const DEFAULT_SETTINGS = Object.freeze({
    receiverUrl: '',
    pollIntervalMs: 2500,
    timeoutMs: 120000,
  });

  function asPromise(value) {
    return value && typeof value.then === 'function' ? value : Promise.resolve(value);
  }

  function storageGet(local, keys) {
    return new Promise((resolve) => local.get(keys, (values) => resolve(values || {})));
  }

  function storageSet(local, values) {
    return new Promise((resolve) => local.set(values, resolve));
  }

  function storageRemove(local, keys) {
    return new Promise((resolve) => local.remove(keys, resolve));
  }

  function installStorageBridge(root, adapters) {
    const listeners = new Set();

    async function read(keys) {
      if (keys === null || keys === undefined) {
        const value = await asPromise(adapters.getValue(SETTINGS_KEY));
        return value === undefined ? {} : { [SETTINGS_KEY]: value };
      }
      if (typeof keys === 'string') {
        const value = await asPromise(adapters.getValue(keys));
        return value === undefined ? {} : { [keys]: value };
      }
      if (Array.isArray(keys)) {
        const entries = await Promise.all(keys.map(async (key) => [key, await asPromise(adapters.getValue(key))]));
        return Object.fromEntries(entries.filter(([, value]) => value !== undefined));
      }
      if (typeof keys === 'object') {
        const entries = await Promise.all(Object.entries(keys).map(async ([key, fallback]) => [
          key,
          await asPromise(adapters.getValue(key, fallback)),
        ]));
        return Object.fromEntries(entries);
      }
      return {};
    }

    function notify(changes) {
      listeners.forEach((listener) => {
        try {
          listener(changes, 'local');
        } catch (_error) {
          // A faulty listener must not block the content script.
        }
      });
    }

    function finish(promise, callback, fallback) {
      promise.then((value) => callback?.(value)).catch(() => callback?.(fallback));
    }

    const local = {
      get(keys, callback) {
        finish(read(keys), callback, {});
      },
      set(values, callback) {
        finish((async () => {
          const changes = {};
          for (const [key, newValue] of Object.entries(values || {})) {
            const oldValue = await asPromise(adapters.getValue(key));
            await asPromise(adapters.setValue(key, newValue));
            changes[key] = { oldValue, newValue };
          }
          if (Object.keys(changes).length) notify(changes);
        })(), callback);
      },
      remove(keys, callback) {
        const keyList = Array.isArray(keys) ? keys : [keys];
        finish((async () => {
          const changes = {};
          for (const key of keyList.filter(Boolean)) {
            const oldValue = await asPromise(adapters.getValue(key));
            await asPromise(adapters.deleteValue(key));
            changes[key] = { oldValue, newValue: undefined };
          }
          if (Object.keys(changes).length) notify(changes);
        })(), callback);
      },
    };

    const storage = {
      local,
      onChanged: {
        addListener(listener) { listeners.add(listener); },
        removeListener(listener) { listeners.delete(listener); },
      },
    };

    return { local, storage };
  }

  async function readSettings(local) {
    const values = await storageGet(local, SETTINGS_KEY);
    return { ...DEFAULT_SETTINGS, ...(values[SETTINGS_KEY] || {}) };
  }

  function responseContentType(rawHeaders) {
    return String(rawHeaders || '').match(/^content-type\s*:\s*([^\r\n]+)/im)?.[1]?.trim() || '';
  }

  function requestReceiver(adapters, url) {
    return new Promise((resolve) => {
      let settled = false;
      const finish = (result) => {
        if (settled) return;
        settled = true;
        resolve(result);
      };

      try {
        adapters.xmlHttpRequest({
          method: 'GET',
          url,
          timeout: 12000,
          anonymous: true,
          headers: {
            Accept: 'application/json,text/plain,text/html;q=0.9,*/*;q=0.8',
            'Cache-Control': 'no-cache',
          },
          onload(response) {
            const status = Number(response?.status) || 0;
            if (status < 200 || status >= 300) {
              finish({ ok: false, error: `接码接口返回 HTTP ${status || '未知'}`, retryable: status >= 500 });
              return;
            }
            const rawText = String(response?.responseText || '');
            if (rawText.length > 500000) {
              finish({ ok: false, error: '接码接口返回内容过大', retryable: false });
              return;
            }
            finish({ ok: true, rawText, contentType: responseContentType(response?.responseHeaders) });
          },
          ontimeout() {
            finish({ ok: false, error: '请求接码接口超时', retryable: true });
          },
          onerror() {
            finish({ ok: false, error: '无法访问接码接口', retryable: true });
          },
          onabort() {
            finish({ ok: false, error: '接码接口请求已取消', retryable: true });
          },
        });
      } catch (_error) {
        finish({ ok: false, error: '无法访问接码接口', retryable: true });
      }
    });
  }

  async function fetchOtpSnapshot(core, local, adapters, explicitUrl) {
    const settings = await readSettings(local);
    const validation = core.validateReceiverUrl(explicitUrl || settings.receiverUrl);
    if (!validation.ok) return validation;

    const response = await requestReceiver(adapters, validation.url);
    if (!response.ok) return response;
    const parsed = core.parseReceiverResponse(response.rawText, response.contentType);
    return {
      ok: true,
      found: parsed.found,
      code: parsed.code,
      digits: parsed.digits,
      fingerprint: parsed.fingerprint,
      format: parsed.format,
    };
  }

  function installChromeBridge(root, adapters, core, version = '') {
    const bridge = installStorageBridge(root, adapters);
    const runtime = {
      ...(root.chrome?.runtime || {}),
      lastError: null,
      getManifest: () => ({
        name: 'Xynigo SHEIN 店铺接码助手',
        version,
        version_name: `${version}-tampermonkey`,
      }),
      sendMessage(message, callback) {
        const run = async () => {
          switch (message?.type) {
            case 'GET_STATUS': {
              const settings = await readSettings(bridge.local);
              return {
                ok: true,
                configured: Boolean(settings.receiverUrl),
                pollIntervalMs: settings.pollIntervalMs,
                timeoutMs: settings.timeoutMs,
              };
            }
            case 'GET_CONFIG': {
              const settings = await readSettings(bridge.local);
              return { ok: true, receiverUrl: settings.receiverUrl };
            }
            case 'SAVE_CONFIG': {
              const validation = core.validateReceiverUrl(message.receiverUrl);
              if (!validation.ok) return validation;
              await storageSet(bridge.local, {
                [SETTINGS_KEY]: { ...DEFAULT_SETTINGS, receiverUrl: validation.url },
              });
              return { ok: true };
            }
            case 'CLEAR_CONFIG':
              await storageRemove(bridge.local, SETTINGS_KEY);
              return { ok: true };
            case 'TEST_RECEIVER': {
              const snapshot = await fetchOtpSnapshot(core, bridge.local, adapters, message.receiverUrl);
              if (!snapshot.ok) return snapshot;
              return { ok: true, found: snapshot.found, digits: snapshot.digits, format: snapshot.format };
            }
            case 'FETCH_OTP':
              return fetchOtpSnapshot(core, bridge.local, adapters);
            default:
              return { ok: false, error: '不支持的操作' };
          }
        };

        run().then((response) => callback?.(response)).catch(() => {
          callback?.({ ok: false, error: '接码助手内部异常' });
        });
      },
    };

    const chromeBridge = { ...(root.chrome || {}), runtime, storage: bridge.storage };
    try {
      root.chrome = chromeBridge;
    } catch (_error) {
      Object.defineProperty(root, 'chrome', { configurable: true, value: chromeBridge });
    }
    return { ...bridge, runtime };
  }

  function injectCss(root, css, addStyle) {
    if (typeof addStyle === 'function') {
      addStyle(css);
      return;
    }
    const style = root.document?.createElement?.('style');
    if (!style) return;
    style.textContent = css;
    (root.document.head || root.document.documentElement)?.appendChild(style);
  }

  function sendRuntimeMessage(runtime, message) {
    return new Promise((resolve) => runtime.sendMessage(message, (response) => resolve(response || {})));
  }

  function registerMenus(root, runtime, adapters) {
    if (typeof adapters.registerMenuCommand !== 'function') return;

    adapters.registerMenuCommand('配置 SHEIN 接码链接', async () => {
      const receiverUrl = root.prompt?.(
        '请粘贴当前店铺的完整接码链接。为保护私密 key，已有配置不会显示；取消可保留原配置。',
        '',
      );
      if (receiverUrl === null || !String(receiverUrl).trim()) return;
      const result = await sendRuntimeMessage(runtime, { type: 'SAVE_CONFIG', receiverUrl });
      root.alert?.(result.ok ? '接码链接已保存。' : result.error || '接码链接保存失败。');
    });

    adapters.registerMenuCommand('测试 SHEIN 接码链接', async () => {
      const result = await sendRuntimeMessage(runtime, { type: 'TEST_RECEIVER' });
      if (!result.ok) {
        root.alert?.(result.error || '接码链接测试失败。');
        return;
      }
      root.alert?.(
        result.found
          ? `链接可访问，已识别 ${result.digits} 位验证码（验证码内容不显示）。`
          : '链接可访问，当前尚未检测到验证码。',
      );
    });

    adapters.registerMenuCommand('清除 SHEIN 接码链接', async () => {
      if (!root.confirm?.('确认清除当前浏览器环境保存的接码链接？')) return;
      await sendRuntimeMessage(runtime, { type: 'CLEAR_CONFIG' });
      root.alert?.('接码链接已清除。');
    });
  }

  function browserAdapters() {
    return {
      getValue: (...args) => GM_getValue(...args),
      setValue: (...args) => GM_setValue(...args),
      deleteValue: (...args) => GM_deleteValue(...args),
      addStyle: (...args) => GM_addStyle(...args),
      registerMenuCommand: (...args) => GM_registerMenuCommand(...args),
      xmlHttpRequest: (...args) => GM_xmlhttpRequest(...args),
    };
  }

  function boot(root, css, version, adapters) {
    const bridge = installChromeBridge(root, adapters, root.SheinOtpCore, version);
    injectCss(root, css, adapters.addStyle);
    registerMenus(root, bridge.runtime, adapters);
    return bridge;
  }

  return {
    SETTINGS_KEY,
    DEFAULT_SETTINGS,
    asPromise,
    browserAdapters,
    fetchOtpSnapshot,
    installChromeBridge,
    installStorageBridge,
    registerMenus,
    requestReceiver,
    responseContentType,
    boot,
  };
});

'use strict';

(function exposeOtpCore(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.SheinOtpCore = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createOtpCore() {
  const RECEIVER_HOST = 'api.68sms.com';
  const RECEIVER_PATH = '/api/sms/get';
  const OTP_KEY_PATTERN = /^(?:otp|otpcode|verifycode|verificationcode|smscode|captcha|securitycode)$/i;
  const MESSAGE_KEY_PATTERN = /(?:content|message|msg|sms|text|body|data|result)/i;
  const OTP_KEYWORDS = /(?:验证码|驗證碼|校验码|校驗碼|动态码|動態碼|\botp\b|verification\s*code|verify\s*code|security\s*code|passcode)/i;
  const PHONE_KEYWORDS = /(?:手机号|手機號|电话|電話|mobile|phone|tel)/i;
  const TIME_KEYWORDS = /(?:订单|訂單|时间|時間|日期|order|date|time|timestamp)/i;

  function normalizeDigits(value) {
    return String(value == null ? '' : value).replace(/[\uff10-\uff19]/g, (digit) =>
      String.fromCharCode(digit.charCodeAt(0) - 0xfee0),
    );
  }

  function stripMarkup(value) {
    return normalizeDigits(value)
      .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
      .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
      .replace(/<[^>]+>/g, ' ')
      .replace(/&nbsp;|&#160;/gi, ' ')
      .replace(/&amp;/gi, '&')
      .replace(/&lt;/gi, '<')
      .replace(/&gt;/gi, '>')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function stableFingerprint(value) {
    const input = String(value == null ? '' : value);
    let hash = 0x811c9dc5;
    for (let index = 0; index < input.length; index += 1) {
      hash ^= input.charCodeAt(index);
      hash = Math.imul(hash, 0x01000193);
    }
    return (hash >>> 0).toString(16).padStart(8, '0');
  }

  function validateReceiverUrl(rawUrl) {
    const value = String(rawUrl || '').trim();
    if (!value) return { ok: false, error: '请先填写接码链接' };

    let parsed;
    try {
      parsed = new URL(value);
    } catch {
      return { ok: false, error: '接码链接格式不正确' };
    }

    if (parsed.protocol !== 'https:') {
      return { ok: false, error: '接码链接必须使用 HTTPS' };
    }
    if (parsed.hostname.toLowerCase() !== RECEIVER_HOST) {
      return { ok: false, error: '开发版仅支持 api.68sms.com 接码链接' };
    }
    if (parsed.pathname !== RECEIVER_PATH) {
      return { ok: false, error: '接码链接路径应为 /api/sms/get' };
    }
    if (!parsed.searchParams.get('key')) {
      return { ok: false, error: '接码链接缺少 key 参数' };
    }
    return { ok: true, url: parsed.toString() };
  }

  function addTextCandidates(text, candidates, source, baseScore) {
    const clean = stripMarkup(text);
    if (!clean) return;

    const exact = clean.match(/^\D*(\d{4,8})\D*$/);
    if (exact && clean.replace(/\D/g, '').length === exact[1].length) {
      candidates.push({ code: exact[1], score: baseScore + 100, source });
      return;
    }

    const matches = clean.matchAll(/(^|\D)(\d{4,8})(?!\d)/g);
    for (const match of matches) {
      const code = match[2];
      const start = Math.max(0, (match.index || 0) - 70);
      const end = Math.min(clean.length, (match.index || 0) + match[0].length + 70);
      const context = clean.slice(start, end);
      let score = baseScore;

      if (code.length === 6) score += 26;
      else if (code.length === 4 || code.length === 5 || code.length === 8) score += 12;
      else score += 5;

      if (OTP_KEYWORDS.test(context)) score += 90;
      if (/\bSHEIN\b/i.test(context)) score += 35;
      if (PHONE_KEYWORDS.test(context)) score -= 90;
      if (TIME_KEYWORDS.test(context)) score -= 55;
      if (/^20(?:2\d|3\d)$/.test(code)) score -= 80;

      candidates.push({ code, score, source });
    }
  }

  function collectJsonCandidates(value, path, candidates, depth) {
    if (depth > 8 || value == null) return;

    if (Array.isArray(value)) {
      value.slice(0, 100).forEach((item, index) =>
        collectJsonCandidates(item, `${path}[${index}]`, candidates, depth + 1),
      );
      return;
    }

    if (typeof value === 'object') {
      Object.entries(value).slice(0, 150).forEach(([key, item]) => {
        const compactKey = key.replace(/[_\-\s]/g, '');
        const nextPath = path ? `${path}.${key}` : key;
        if (OTP_KEY_PATTERN.test(compactKey) && ['string', 'number'].includes(typeof item)) {
          const exact = normalizeDigits(item).trim().match(/^\d{4,8}$/);
          if (exact) candidates.push({ code: exact[0], score: 180, source: nextPath });
        }
        if (MESSAGE_KEY_PATTERN.test(key) && ['string', 'number'].includes(typeof item)) {
          addTextCandidates(item, candidates, nextPath, 35);
        }
        collectJsonCandidates(item, nextPath, candidates, depth + 1);
      });
      return;
    }

    if (typeof value === 'string') addTextCandidates(value, candidates, path, 10);
  }

  function parseReceiverResponse(rawText, contentType) {
    const text = String(rawText == null ? '' : rawText).slice(0, 500000);
    const candidates = [];
    let format = 'text';
    let parsedJson = null;

    if (/json/i.test(String(contentType || '')) || /^[\s\uFEFF]*[\[{]/.test(text)) {
      try {
        parsedJson = JSON.parse(text);
        format = 'json';
      } catch {
        format = 'text';
      }
    }

    if (parsedJson !== null) collectJsonCandidates(parsedJson, '', candidates, 0);
    addTextCandidates(text, candidates, 'response', format === 'json' ? 0 : 10);

    const deduped = new Map();
    candidates.forEach((candidate) => {
      const previous = deduped.get(candidate.code);
      if (!previous || candidate.score > previous.score) deduped.set(candidate.code, candidate);
    });

    const ranked = [...deduped.values()].sort((left, right) => right.score - left.score);
    const best = ranked.find((candidate) => candidate.score >= 45) || null;
    return {
      found: Boolean(best),
      code: best ? best.code : null,
      digits: best ? best.code.length : 0,
      format,
      fingerprint: stableFingerprint(`${best ? best.code : ''}|${stripMarkup(text).slice(0, 4000)}`),
    };
  }

  return {
    parseReceiverResponse,
    stableFingerprint,
    stripMarkup,
    validateReceiverUrl,
  };
});

'use strict';

(function exposePageState(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.SheinOtpPageState = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createPageState() {
  const SENT_MARKER = /(?:验证码已发送|驗證碼已發送|已发送验证码|已發送驗證碼|verification\s*code\s*(?:has\s*been\s*)?sent|code\s*(?:has\s*been\s*)?sent)/i;
  const COUNTDOWN_MARKER = /(?:^|\s)(\d{1,3})\s*(?:s|秒)(?=\s|$)/i;

  function normalizeText(value) {
    return String(value || '').replace(/\s+/g, ' ').trim();
  }

  function detectDispatchState({ text, getCodeButtonVisible = false } = {}) {
    const normalized = normalizeText(text);
    const hasSentMarker = SENT_MARKER.test(normalized);
    const countdownMatch = normalized.match(COUNTDOWN_MARKER);
    const hasCountdown = Boolean(countdownMatch);
    const countdownSeconds = countdownMatch ? Number(countdownMatch[1]) : null;
    return {
      autoSent: hasSentMarker || (hasCountdown && !getCodeButtonVisible),
      hasSentMarker,
      hasCountdown,
      countdownSeconds,
    };
  }

  return { detectDispatchState, normalizeText };
});

globalThis.XynigoSheinOtpUserscriptRuntime.boot(globalThis, "#shein-otp-assistant-root {\n  position: fixed;\n  right: 24px;\n  top: 24px;\n  z-index: 2147483647;\n  pointer-events: none;\n}\n\n@media (max-width: 720px) {\n  #shein-otp-assistant-root {\n    left: 16px;\n    right: 16px;\n    top: 16px;\n  }\n}\n", "0.1.1", globalThis.XynigoSheinOtpUserscriptRuntime.browserAdapters());

'use strict';

(() => {
  const OTP_INPUT_SELECTORS = [
    'input#verifyCode',
    'input[placeholder*="短信验证码"]',
    'input[autocomplete="one-time-code"]',
  ];
  const GET_CODE_LABELS = [
    '获取验证码',
    '获取驗證碼',
    'get verification code',
    'get code',
    'send code',
  ];

  const state = {
    activeInput: null,
    autoTriggeredInputs: new WeakSet(),
    baselineReady: false,
    baselineCode: null,
    lastSeenCode: null,
    primePromise: null,
    sessionId: 0,
    widget: null,
  };

  function sendMessage(message) {
    return new Promise((resolve) => {
      chrome.runtime.sendMessage(message, (response) => {
        if (chrome.runtime.lastError) {
          resolve({ ok: false, error: '插件通信失败' });
          return;
        }
        resolve(response || { ok: false, error: '插件未返回结果' });
      });
    });
  }

  function normalizeLabel(value) {
    return String(value || '').replace(/\s+/g, ' ').trim().toLowerCase();
  }

  function isVisible(element) {
    if (!(element instanceof HTMLElement)) return false;
    const style = window.getComputedStyle(element);
    return style.display !== 'none' && style.visibility !== 'hidden' && element.getClientRects().length > 0;
  }

  function findOtpInput() {
    for (const selector of OTP_INPUT_SELECTORS) {
      const inputs = [...document.querySelectorAll(selector)];
      const visibleInput = inputs.find((input) => input instanceof HTMLInputElement && isVisible(input));
      if (visibleInput) return visibleInput;
    }
    return null;
  }

  function getOtpDialogScope(input) {
    return (
      input.closest('.soui-dialog, [role="dialog"], [aria-modal="true"], [class*="modal"]') ||
      input.parentElement?.parentElement?.parentElement?.parentElement ||
      document.body
    );
  }

  function getDispatchEvidence(input) {
    const scope = getOtpDialogScope(input);
    const scopeButtons = [...scope.querySelectorAll('button')];
    const getCodeButtonVisible = scopeButtons.some((button) => {
      const label = normalizeLabel(button.textContent);
      return isVisible(button) && GET_CODE_LABELS.some((candidate) => label === candidate || label.includes(candidate));
    });
    const scopeState = SheinOtpPageState.detectDispatchState({
      text: scope.innerText || scope.textContent || '',
      getCodeButtonVisible,
    });
    if (scopeState.autoSent) return scopeState;

    const pageState = SheinOtpPageState.detectDispatchState({
      text: document.body?.innerText || '',
      getCodeButtonVisible,
    });
    return pageState.hasSentMarker ? pageState : scopeState;
  }

  function ensureWidget() {
    if (state.widget && state.widget.isConnected) return state.widget;
    const host = document.createElement('div');
    host.id = 'shein-otp-assistant-root';
    const shadow = host.attachShadow({ mode: 'open' });
    shadow.innerHTML = `
      <style>
        :host { all: initial; }
        .notice {
          align-items: center;
          background: #111827;
          border: 1px solid rgba(255,255,255,.16);
          border-radius: 10px;
          box-shadow: 0 12px 30px rgba(15,23,42,.24);
          color: #fff;
          display: flex;
          font: 13px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          gap: 9px;
          max-width: 360px;
          min-height: 20px;
          padding: 10px 13px;
        }
        .dot { background: #60a5fa; border-radius: 999px; height: 8px; width: 8px; flex: 0 0 auto; }
        .notice[data-tone="success"] .dot { background: #34d399; }
        .notice[data-tone="warning"] .dot { background: #fbbf24; }
        .notice[data-tone="error"] .dot { background: #fb7185; }
      </style>
      <div class="notice" data-tone="info" role="status" aria-live="polite">
        <span class="dot"></span><span class="text">SHEIN 接码助手已加载</span>
      </div>`;
    (document.documentElement || document.body).appendChild(host);
    state.widget = host;
    return host;
  }

  function setStatus(text, tone = 'info') {
    const widget = ensureWidget();
    const notice = widget.shadowRoot.querySelector('.notice');
    notice.dataset.tone = tone;
    widget.shadowRoot.querySelector('.text').textContent = text;
  }

  function setNativeInputValue(input, value) {
    const ownSetter = Object.getOwnPropertyDescriptor(input, 'value')?.set;
    const prototypeSetter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set;
    if (prototypeSetter && ownSetter !== prototypeSetter) prototypeSetter.call(input, value);
    else if (ownSetter) ownSetter.call(input, value);
    else input.value = value;

    input.dispatchEvent(
      new InputEvent('input', { bubbles: true, composed: true, data: value, inputType: 'insertText' }),
    );
    input.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    input.focus({ preventScroll: true });
  }

  async function primeBaseline({ announce = false } = {}) {
    if (state.baselineReady) {
      if (announce) setStatus('已就绪，等待 SHEIN 发送验证码');
      return;
    }
    if (state.primePromise) return state.primePromise;
    state.primePromise = (async () => {
      const status = await sendMessage({ type: 'GET_STATUS' });
      if (!status.ok || !status.configured) {
        state.baselineReady = false;
        if (announce) setStatus('未配置接码链接，请打开接码助手配置', 'warning');
        return;
      }

      const snapshot = await sendMessage({ type: 'FETCH_OTP' });
      if (snapshot.ok) {
        state.baselineReady = true;
        state.baselineCode = snapshot.found ? snapshot.code : null;
        state.lastSeenCode = state.baselineCode;
        if (announce) setStatus('已就绪，等待 SHEIN 发送验证码');
      } else if (announce) {
        setStatus(`${snapshot.error || '接码接口异常'}，可继续尝试`, 'warning');
      }
    })().finally(() => {
      state.primePromise = null;
    });
    return state.primePromise;
  }

  async function pollForOtp(input, { trigger = 'manual' } = {}) {
    const sessionId = ++state.sessionId;
    const status = await sendMessage({ type: 'GET_STATUS' });
    if (!status.ok || !status.configured) {
      setStatus('未配置接码链接，请打开接码助手配置', 'warning');
      return;
    }

    if (state.primePromise) await state.primePromise;
    if (sessionId !== state.sessionId) return;

    if (!state.baselineReady) {
      const baseline = await sendMessage({ type: 'FETCH_OTP' });
      if (sessionId !== state.sessionId) return;
      if (baseline.ok) {
        state.baselineReady = true;
        state.baselineCode = baseline.found ? baseline.code : null;
        state.lastSeenCode = state.baselineCode;
      }
    }

    const baselineCode = state.lastSeenCode || state.baselineCode || null;
    const startedAt = Date.now();
    const timeoutMs = Number(status.timeoutMs) || 120000;
    const intervalMs = Number(status.pollIntervalMs) || 2500;
    let failures = 0;

    setStatus(
      trigger === 'automatic'
        ? '检测到 SHEIN 已自动发送验证码，正在自动接码…'
        : '已检测到“获取验证码”，正在等待新短信…',
    );
    await new Promise((resolve) => window.setTimeout(resolve, 900));

    while (sessionId === state.sessionId && Date.now() - startedAt < timeoutMs) {
      if (!input.isConnected || !isVisible(input)) {
        setStatus('验证码窗口已关闭，已停止接码', 'warning');
        return;
      }

      const snapshot = await sendMessage({ type: 'FETCH_OTP' });
      if (sessionId !== state.sessionId) return;

      if (snapshot.ok) {
        failures = 0;
        if (snapshot.found) {
          state.lastSeenCode = snapshot.code;
          if (!baselineCode || snapshot.code !== baselineCode) {
            setNativeInputValue(input, snapshot.code);
            state.baselineCode = snapshot.code;
            state.baselineReady = true;
            setStatus(`已自动填入 ${snapshot.digits} 位验证码，请手动点击“确认”`, 'success');
            return;
          }
        }
        const seconds = Math.max(1, Math.round((Date.now() - startedAt) / 1000));
        setStatus(`正在等待新短信… ${seconds} 秒`);
      } else {
        failures += 1;
        setStatus(`${snapshot.error || '接码接口异常'}，正在重试`, failures >= 3 ? 'error' : 'warning');
      }

      await new Promise((resolve) => window.setTimeout(resolve, intervalMs));
    }

    if (sessionId === state.sessionId) {
      setStatus('120 秒内未收到新验证码，可重新点击“获取验证码”', 'error');
    }
  }

  function inspectPage() {
    const input = findOtpInput();
    if (!input) {
      if (state.activeInput && !state.activeInput.isConnected) {
        state.sessionId += 1;
        state.activeInput = null;
      }
      return;
    }

    const inputChanged = state.activeInput !== input;
    if (state.activeInput !== input) {
      state.sessionId += 1;
      state.activeInput = input;
    }

    const dispatchEvidence = getDispatchEvidence(input);
    if (dispatchEvidence.autoSent && !state.autoTriggeredInputs.has(input)) {
      state.autoTriggeredInputs.add(input);
      void pollForOtp(input, { trigger: 'automatic' });
      return;
    }

    if (inputChanged) void primeBaseline({ announce: true });
  }

  document.addEventListener(
    'click',
    (event) => {
      const button = event.target instanceof Element ? event.target.closest('button') : null;
      if (!button) return;
      const label = normalizeLabel(button.textContent);
      if (!GET_CODE_LABELS.some((candidate) => label === candidate || label.includes(candidate))) return;
      const input = findOtpInput();
      if (!input) return;
      state.activeInput = input;
      state.autoTriggeredInputs.add(input);
      void pollForOtp(input, { trigger: 'manual' });
    },
    true,
  );

  chrome.storage.onChanged.addListener((changes, areaName) => {
    if (areaName !== 'local' || !changes.sheinOtpAssistantSettings) return;
    state.sessionId += 1;
    state.baselineReady = false;
    state.baselineCode = null;
    state.lastSeenCode = null;
    const input = findOtpInput();
    if (input) {
      state.activeInput = input;
      void inspectPage();
    } else {
      void primeBaseline({ announce: false });
    }
  });

  const observer = new MutationObserver(inspectPage);
  function startObserver() {
    if (!document.documentElement) {
      window.setTimeout(startObserver, 0);
      return;
    }
    observer.observe(document.documentElement, { childList: true, subtree: true });
    void primeBaseline({ announce: false });
    inspectPage();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inspectPage, { once: true });
  }
  startObserver();
})();
