// ==UserScript==
// @name         Xynigo SHEIN Captcha Auto Solver
// @namespace    https://github.com/wrangler1024/crossborder-userscripts
// @version      0.4.0
// @description  选品过程中按页面规则自动处理 SHEIN nine-captcha 九宫格验证码：视觉模型可配置（智谱/豆包/Gemini/自定义），支持双模型对比与样本回放。
// @author       Samforo
// @homepageURL  https://github.com/wrangler1024/crossborder-userscripts/tree/main/scripts/shein-captcha-solver
// @supportURL   https://github.com/wrangler1024/crossborder-userscripts/issues
// @match        https://us.shein.com/*
// @match        https://shein.com.mx/*
// @match        https://*.shein.com.mx/*
// @icon         https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/assets/xynigo-mascot.png
// @grant        GM_xmlhttpRequest
// @grant        GM_registerMenuCommand
// @connect      open.bigmodel.cn
// @connect      ark.cn-beijing.volces.com
// @connect      generativelanguage.googleapis.com
// @connect      us.shein.com
// @connect      *.shein.com
// @connect      shein.com.mx
// @connect      *.shein.com.mx
// @connect      *.ltwebstatic.com
// @run-at       document-idle
// @downloadURL  https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/scripts/shein-captcha-solver/xynigo_shein_captcha_solver.user.js
// @updateURL    https://raw.githubusercontent.com/wrangler1024/crossborder-userscripts/main/scripts/shein-captcha-solver/xynigo_shein_captcha_solver.user.js
// ==/UserScript==

// Generated from the shared Manifest V3 source. Do not edit this file by hand.
globalThis.__xynigoCaptchaVersion = "0.4.0";
'use strict';

// Tampermonkey 运行时桥接：在 userscript 环境里装一个与 MV3 同形的 chrome 对象，
// 让 src/ 的 content.js / captcha-agent.js 无差别运行。识别请求经 GM_xmlhttpRequest 绕 CORS。
(function exposeXynigoCaptchaUserscriptRuntime(rootMod, factory) {
    const api = factory(rootMod);
    if (typeof module === 'object' && module.exports) module.exports = api;
    rootMod.XynigoCaptchaUserscriptRuntime = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createRuntime(globalRef) {

    const CONFIG_KEY = 'xynigoCaptchaConfig';
    const LOGS_KEY = 'xynigoCaptchaLogs';
    const SAMPLES_KEY = 'xynigoCaptchaSamples';
    const LOGS_CAP = 500;

    function gmFetch(options) {
        if (typeof GM_xmlhttpRequest !== 'function') {
            return Promise.reject(new Error('当前环境无 GM_xmlhttpRequest，无法跨域请求。'));
        }
        return new Promise((resolve, reject) => {
            GM_xmlhttpRequest({
                method: options.method || 'GET',
                url: options.url,
                headers: options.headers || {},
                data: options.data != null ? String(options.data) : undefined,
                responseType: options.responseType,
                timeout: options.timeout || 60000,
                onload: resolve,
                onerror: () => reject(new Error('网络请求失败')),
                ontimeout: () => reject(new Error('网络请求超时')),
            });
        });
    }

    function blobToDataUrl(blob) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(String(reader.result));
            reader.onerror = () => reject(new Error('图片转码失败'));
            reader.readAsDataURL(blob);
        });
    }

    function storageGet(key, fallback) {
        try {
            const raw = globalRef.localStorage.getItem(key);
            return raw == null ? fallback : JSON.parse(raw);
        } catch (_error) {
            return fallback;
        }
    }

    function storageSet(key, value) {
        try {
            globalRef.localStorage.setItem(key, JSON.stringify(value));
            return true;
        } catch (_error) {
            return false;
        }
    }

    // 识别调用直接在 userscript 侧执行（与 background 同一套 vision-client）。
    async function handleSolve(message) {
        const Config = globalRef.XynigoCaptchaConfig;
        const Puzzle = globalRef.XynigoCaptchaPuzzle;
        const Vision = globalRef.XynigoCaptchaVision;
        const config = message.configOverride ? Config.normalizeConfig(message.configOverride) : Config.normalizeConfig(storageGet(CONFIG_KEY, {}));
        const callWith = async (cfg) => {
            const result = await Vision.callVisionModel(cfg, message.image, message.prompt || Puzzle.PROMPT, (url, requestOptions) => gmFetch({
                url,
                method: requestOptions.method,
                headers: requestOptions.headers,
                data: requestOptions.body,
                timeout: 60000,
            }).then((response) => ({
                ok: response.status >= 200 && response.status < 300,
                status: response.status,
                text: () => Promise.resolve(String(response.responseText || '')),
            })));
            if (!result.ok) return { ok: false, text: '', latencyMs: result.latencyMs, error: result.error || '识别失败' };
            try {
                return { ok: true, text: result.text, latencyMs: result.latencyMs, answer: Puzzle.parseModelAnswer(result.text).matches, error: '' };
            } catch (error) {
                return { ok: true, text: result.text, latencyMs: result.latencyMs, answer: [], parseError: error.message, error: '' };
            }
        };
        const primary = await callWith(config);
        let shadow = null;
        let compare = null;
        if (config.compareEnabled) {
            const compareConfig = Config.effectiveCompareConfig(config);
            shadow = await callWith(compareConfig);
            compare = { provider: compareConfig.provider, model: compareConfig.model };
        }
        return { ok: true, primary, shadow, compare, config: { provider: config.provider, model: config.model } };
    }

    function appendCapped(key, records, cap) {
        const list = storageGet(key, []);
        records.forEach((record) => list.push(record));
        while (list.length > cap) list.shift();
        storageSet(key, list);
    }

    // 把 GM 版消息处理装成 chrome.runtime.sendMessage 同形接口。
    function createChromeShim() {
        async function dispatch(message) {
            switch (message.type) {
                case 'captchaGetConfig':
                case 'captchaGetAll': {
                    const config = globalRef.XynigoCaptchaConfig.normalizeConfig(storageGet(CONFIG_KEY, {}));
                    if (message.type === 'captchaGetConfig') return { ok: true, config };
                    return { ok: true, config, logs: storageGet(LOGS_KEY, []), samples: storageGet(SAMPLES_KEY, []) };
                }
                case 'captchaSaveConfig': {
                    const config = globalRef.XynigoCaptchaConfig.normalizeConfig(message.config);
                    storageSet(CONFIG_KEY, config);
                    return { ok: true, config };
                }
                case 'captchaFetchImage': {
                    const response = await gmFetch({ method: 'GET', url: message.url, responseType: 'blob', timeout: 30000 });
                    if (response.status !== 200) throw new Error(`图片拉取 HTTP ${response.status}`);
                    return { ok: true, dataUrl: await blobToDataUrl(response.response) };
                }
                case 'captchaSolve':
                    return handleSolve(message);
                case 'captchaTestConnection': {
                    const config = globalRef.XynigoCaptchaConfig.normalizeConfig(message.config);
                    const result = await globalRef.XynigoCaptchaVision.callVisionModel(config, message.image, message.prompt || 'Reply with OK.', (url, requestOptions) => gmFetch({
                        url, method: requestOptions.method, headers: requestOptions.headers, data: requestOptions.body,
                    }).then((response) => ({
                        ok: response.status >= 200 && response.status < 300,
                        status: response.status,
                        text: () => Promise.resolve(String(response.responseText || '')),
                    })));
                    return { ok: result.ok, text: result.text, latencyMs: result.latencyMs, error: result.error, status: result.status };
                }
                case 'captchaAppendLogs':
                    appendCapped(LOGS_KEY, message.records || [], LOGS_CAP);
                    return { ok: true };
                case 'captchaAppendSample': {
                    const sample = message.sample || {};
                    const config = globalRef.XynigoCaptchaConfig.normalizeConfig(storageGet(CONFIG_KEY, {}));
                    appendCapped(SAMPLES_KEY, [sample], Math.min(config.maxSamples || 50, 200));
                    return { ok: true };
                }
                case 'captchaClear':
                    storageSet(message.target === 'samples' ? SAMPLES_KEY : LOGS_KEY, []);
                    return { ok: true };
                default:
                    throw new Error('未知消息类型：' + message.type);
            }
        }

        return {
            runtime: {
                id: 'xynigo-captcha-userscript',
                getManifest: () => ({ version: globalRef.__xynigoCaptchaVersion || '0.0.0' }),
                sendMessage(message, callback) {
                    dispatch(message).then(
                        (result) => callback && callback(result),
                        (error) => {
                            if (callback) {
                                globalRef.chrome.runtime.lastError = { message: String((error && error.message) || error) };
                                try { callback(undefined); } finally { globalRef.chrome.runtime.lastError = null; }
                            }
                        },
                    );
                },
            },
            permissions: {
                contains: async () => true,
                request: async () => true,
            },
        };
    }

    function install() {
        if (typeof GM_registerMenuCommand === 'function') {
            GM_registerMenuCommand('编辑模型配置（JSON）', () => {
                const Config = globalRef.XynigoCaptchaConfig;
                const current = Config.normalizeConfig(storageGet(CONFIG_KEY, {}));
                const input = globalRef.prompt(
                    '识别模型配置 JSON（provider: zhipu/doubao/gemini/custom；对比模型 compare* 字段；仅保存在本机）：',
                    JSON.stringify({
                        provider: current.provider, baseUrl: current.baseUrl, model: current.model, apiKey: current.apiKey,
                        compareEnabled: current.compareEnabled, compareProvider: current.compare.provider,
                        compareBaseUrl: current.compare.baseUrl, compareModel: current.compare.model,
                        compareApiKey: current.compare.apiKey, collectSamples: current.collectSamples,
                    }, null, 1),
                );
                if (input == null) return;
                try {
                    const next = Config.normalizeConfig(JSON.parse(input));
                    storageSet(CONFIG_KEY, next);
                    globalRef.alert('配置已保存：' + next.provider + ' / ' + next.model);
                } catch (error) {
                    globalRef.alert('配置解析失败：' + error.message);
                }
            });
        }
        globalRef.chrome = createChromeShim();
    }

    return { install };
});

'use strict';

// 识别模型配置：所有 provider 统一走 OpenAI 兼容 /chat/completions。
(function exposeCaptchaConfig(root, factory) {
    const api = factory();
    if (typeof module === 'object' && module.exports) module.exports = api;
    root.XynigoCaptchaConfig = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createConfig() {

    // 预置 provider：baseUrl 到 chat/completions 的拼接规则见 vision-client。
    const PROVIDER_PRESETS = Object.freeze({
        zhipu: {
            label: '智谱 GLM（免费档）',
            baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
            models: ['glm-4v-flash', 'glm-4.6v-flash', 'glm-4.1v-thinking-flash'],
            keyHint: 'open.bigmodel.cn 控制台创建 API Key，glm-4v-flash / glm-4.6v-flash 免费调用。',
        },
        doubao: {
            label: '豆包 · 火山方舟',
            baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
            models: ['doubao-seed-1.8', 'doubao-seed-1.6-vision'],
            keyHint: '火山方舟需实名认证并创建推理接入点；model 填 ep-xxxx 或模型名。',
        },
        gemini: {
            label: 'Google Gemini（国际）',
            baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
            models: ['gemini-2.5-flash', 'gemini-2.5-flash-lite'],
            keyHint: 'Google AI Studio 创建 API Key；免费档约 5-15 RPM。',
        },
        custom: {
            label: '自定义（OpenAI 兼容）',
            baseUrl: '',
            models: [],
            keyHint: 'Base URL 需兼容 OpenAI /chat/completions 协议。',
        },
    });

    const STORAGE_KEYS = Object.freeze({
        config: 'xynigoCaptchaConfig',
        logs: 'xynigoCaptchaLogs',
        samples: 'xynigoCaptchaSamples',
    });

    const DEFAULT_CONFIG = Object.freeze({
        provider: 'zhipu',
        baseUrl: PROVIDER_PRESETS.zhipu.baseUrl,
        model: 'glm-4v-flash',
        apiKey: '',
        autoSolve: true,
        maxRounds: 3,
        settleTimeoutMs: 8000,
        // 对比模式：同一张拼图并行发给第二组模型，只记录不点击，用于配对比较。
        compareEnabled: false,
        compareProvider: 'zhipu',
        compareBaseUrl: PROVIDER_PRESETS.zhipu.baseUrl,
        compareModel: 'glm-4.6v-flash',
        compareApiKey: '',
        // 样本采集：解题通过的拼图 + 金标准编号落盘，供回放评测。
        collectSamples: true,
        maxSamples: 50,
    });

    const LIMITS = Object.freeze({
        maxLogs: 500,
        maxSamples: 200,
        sampleMaxChars: 400000, // 单样本拼图 dataURL 上限，防止撑爆 storage。
    });

    function clampInt(value, fallback, min, max) {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isFinite(parsed)) return fallback;
        return Math.min(max, Math.max(min, parsed));
    }

    function asBool(value, fallback) {
        if (typeof value === 'boolean') return value;
        if (value === 'true') return true;
        if (value === 'false') return false;
        return fallback;
    }

    function pickProviderFields(source, prefix) {
        const p = prefix || '';
        const provider = String(source[p ? p + 'Provider' : 'provider'] || '').trim();
        const baseUrl = String(source[p ? p + 'BaseUrl' : 'baseUrl'] || '').trim();
        const model = String(source[p ? p + 'Model' : 'model'] || '').trim();
        const apiKey = String(source[p ? p + 'ApiKey' : 'apiKey'] || '').trim();
        const resolvedProvider = PROVIDER_PRESETS[provider]
            ? provider
            : (p ? DEFAULT_CONFIG.compareProvider : DEFAULT_CONFIG.provider);
        const preset = PROVIDER_PRESETS[resolvedProvider];
        return {
            provider: resolvedProvider,
            baseUrl: baseUrl || (preset ? preset.baseUrl : ''),
            model,
            apiKey,
        };
    }

    // 任意来源（storage / 表单 / 旧数据）收敛为合法配置；未知字段丢弃。
    function normalizeConfig(raw) {
        const source = raw && typeof raw === 'object' ? raw : {};
        const primary = pickProviderFields(source, '');
        return {
            provider: primary.provider,
            baseUrl: primary.baseUrl,
            model: primary.model || DEFAULT_CONFIG.model,
            apiKey: primary.apiKey,
            autoSolve: asBool(source.autoSolve, DEFAULT_CONFIG.autoSolve),
            maxRounds: clampInt(source.maxRounds, DEFAULT_CONFIG.maxRounds, 1, 5),
            settleTimeoutMs: clampInt(source.settleTimeoutMs, DEFAULT_CONFIG.settleTimeoutMs, 3000, 30000),
            compareEnabled: asBool(source.compareEnabled, DEFAULT_CONFIG.compareEnabled),
            compare: pickProviderFields(source, 'compare'),
            collectSamples: asBool(source.collectSamples, DEFAULT_CONFIG.collectSamples),
            maxSamples: clampInt(source.maxSamples, DEFAULT_CONFIG.maxSamples, 1, LIMITS.maxSamples),
        };
    }

    // 对比配置若未单独填 key，回落主 key（同 provider 场景最常见）。
    function effectiveCompareConfig(config) {
        const compare = config.compare || {};
        return {
            provider: compare.provider || config.provider,
            baseUrl: compare.baseUrl || config.baseUrl,
            model: compare.model || config.model,
            apiKey: compare.apiKey || config.apiKey,
        };
    }

    return { PROVIDER_PRESETS, STORAGE_KEYS, DEFAULT_CONFIG, LIMITS, normalizeConfig, effectiveCompareConfig };
});

'use strict';

// 九宫格拼图纯逻辑：图分类、编号版式、提示词、答案解析、命中评分。
// 2026-08-21 实测结论：多图直传被智谱 1210 拒绝，须拼成单图并在每格印数字，模型只回编号 JSON。
// 版式与提示词对齐 v0.2.0 已实测的红色编号拼图（384x556）。
(function exposeCaptchaPuzzle(root, factory) {
    const api = factory();
    if (typeof module === 'object') module.exports = api;
    root.XynigoCaptchaPuzzle = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createPuzzle() {

    // 版面：提示图在上（8,24），九宫格在下（行优先编号 1-9），每格左上角印红色编号角标。
    const LAYOUT = Object.freeze({
        canvasWidth: 384,
        canvasHeight: 556,
        margin: 8,
        cell: 120,
        gutter: 4,
        hintRect: Object.freeze({ x: 8, y: 24, w: 120, h: 120 }),
        hintLabelText: '提示图',
        hintLabelPos: Object.freeze({ x: 8, y: 8 }),
        gridLabelText: '九宫格（编号1-9）',
        gridLabelPos: Object.freeze({ x: 8, y: 162 }),
        gridOrigin: Object.freeze({ x: 8, y: 180 }),
        badgeSize: 26,
    });

    const PROMPT_PREFIX = '这是SHEIN验证码拼图：上方是提示图，下方九宫格每格左上角印有红色编号1-9。';
    const OUTPUT_CONTRACT = '只输出JSON，格式：{"targets":[编号]}，不要输出任何其他文字。';
    const DEFAULT_RULE = '请找出所有与提示图同类别的物品所在的格子编号（可能有多个）。';
    const INSTRUCTION_SIGNAL = /seleccion|selección|elige|encuentra|conteng|igual|manzan|sombrer|carta|select|choose|find|contain|same|match|apple|hat|选择|找出|包含|相同|同类/i;
    const CONTROL_ONLY = /^(actualizar|reportar|refresh|report|cancelar|cerrar|close)$/i;

    // 页面标题来自第三方 DOM：只保留短文本验证规则，剔除控件文案和可能改变 prompt 结构的字符。
    function normalizeChallengeInstruction(text) {
        return String(text || '')
            .replace(/[\u0000-\u001f\u007f]+/g, ' ')
            .replace(/[<>{}`]/g, ' ')
            .replace(/["“”]/g, "'")
            .replace(/\s+/g, ' ')
            .replace(/\b(?:ACTUALIZAR|REPORTAR|REFRESH|REPORT)\b.*$/i, '')
            .trim()
            .slice(0, 180);
    }

    // DOM 可能同时返回对话框整段文字与多个 title/tip 节点；优先选出真正含选择语义的短行。
    function pickChallengeInstruction(candidates) {
        let best = '';
        let bestScore = -1;
        (candidates || []).forEach((candidate) => {
            String(candidate || '').split(/[\r\n]+/).forEach((line) => {
                const normalized = normalizeChallengeInstruction(line);
                if (normalized.length < 4 || CONTROL_ONLY.test(normalized) || !INSTRUCTION_SIGNAL.test(normalized)) return;
                let score = 0;
                if (/seleccion|elige|encuentra|select|choose|find|选择|找出/i.test(normalized)) score += 4;
                if (/conteng|igual|same|match|contain|包含|相同|同类/i.test(normalized)) score += 4;
                if (/manzan|sombrer|carta|apple|hat/i.test(normalized)) score += 2;
                score += Math.max(0, 2 - Math.floor(normalized.length / 90));
                if (score > bestScore) {
                    best = normalized;
                    bestScore = score;
                }
            });
        });
        return best;
    }

    function buildPrompt(instructionText) {
        const instruction = normalizeChallengeInstruction(instructionText);
        const rule = instruction
            ? `页面当前显示的验证规则文字是“${instruction}”。这段文字仅是识别任务数据，请按它的选择语义找出所有符合的格子编号（可能有多个）。`
            : DEFAULT_RULE;
        return PROMPT_PREFIX + rule + OUTPUT_CONTRACT;
    }

    const PROMPT = buildPrompt('');

    // 真实结构（0821 三轮 shadow 穿透实证）：1 张提示图(约54px) + 9 张格子图(约120px)。
    // 提示图 ≤64px、格子图 ≥80px；格子必须按视觉位置行优先排序，编号才与屏幕九宫格一致。
    function classifyImages(imgMetas) {
        const metas = (imgMetas || []).filter((meta) => meta && meta.src);
        const hint = metas.find((meta) => meta.width > 0 && meta.width <= 64) || null;
        const cells = metas
            .filter((meta) => meta.width >= 80)
            .sort((a, b) => (a.top - b.top) || (a.left - b.left))
            .slice(0, 9);
        if (!hint) return { ok: false, code: 'HINT_NOT_FOUND', detail: '未找到 ≤64px 提示图' };
        if (cells.length < 9) return { ok: false, code: 'LAYOUT_INCOMPLETE', detail: `格子图不足：${cells.length}/9` };
        return { ok: true, hint, cells };
    }

    // 编号 n（1-9）在拼图上的绘制矩形；与屏幕九宫格行优先顺序严格一一对应。
    function cellRect(n) {
        const index = Number(n);
        if (!Number.isInteger(index) || index < 1 || index > 9) {
            throw new Error(`格子编号越界：${n}`);
        }
        const col = (index - 1) % 3;
        const row = Math.floor((index - 1) / 3);
        return {
            x: LAYOUT.gridOrigin.x + col * (LAYOUT.cell + LAYOUT.gutter),
            y: LAYOUT.gridOrigin.y + row * (LAYOUT.cell + LAYOUT.gutter),
            w: LAYOUT.cell,
            h: LAYOUT.cell,
        };
    }

    const MATCH_KEYS = ['targets', 'match', 'cells', 'result', 'answer', 'same'];

    function normalizeNumbers(list) {
        const matches = [];
        (list || []).forEach((value) => {
            const num = Number.parseInt(value, 10);
            if (Number.isInteger(num) && num >= 1 && num <= 9 && !matches.includes(num)) matches.push(num);
        });
        return matches.sort((a, b) => a - b);
    }

    // 从模型输出稳健提取编号：完整 {...} JSON（targets 键优先）；有残缺 JSON 不做裸数字猜测；
    // 完全无大括号时裸数字兜底（容忍「格子 2 和 5」类自然语言回答）。
    function parseModelAnswer(text) {
        const output = String(text || '').trim();
        if (!output) return { matches: [] };
        const jsonMatch = output.match(/\{[\s\S]*?\}/);
        if (jsonMatch) {
            let parsed;
            try {
                parsed = JSON.parse(jsonMatch[0]);
            } catch (_error) {
                return { matches: [] };
            }
            if (!parsed || typeof parsed !== 'object') return { matches: [] };
            let list = null;
            for (const key of MATCH_KEYS) {
                if (Array.isArray(parsed[key])) { list = parsed[key]; break; }
            }
            if (!list) {
                list = Object.keys(parsed).map((key) => parsed[key]).find(Array.isArray) || null;
            }
            return { matches: list ? normalizeNumbers(list) : [] };
        }
        const digits = output.match(/\d+/g) || [];
        return { matches: normalizeNumbers(digits) };
    }

    // 命中编号 → 页面格子中心坐标（clientX/Y，rects 为点击前实时测量的页面格子矩形，按编号 1-9 行优先）。
    function answerToPoints(matches, cellRects) {
        const points = [];
        (matches || []).forEach((n) => {
            const rect = cellRects[n - 1];
            if (!rect) return;
            points.push({ n, x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 });
        });
        return points;
    }

    // 回放评分：exact=集合全等；precision/recall 按格子级统计。
    function scoreAnswer(answer, groundTruth) {
        const pred = new Set((answer || []).map(Number));
        const truth = new Set((groundTruth || []).map(Number));
        let hit = 0;
        truth.forEach((n) => { if (pred.has(n)) hit += 1; });
        const precision = pred.size ? hit / pred.size : 0;
        const recall = truth.size ? hit / truth.size : 0;
        const exact = pred.size === truth.size && hit === truth.size;
        return { exact, precision, recall, hit };
    }

    return {
        LAYOUT,
        PROMPT,
        normalizeChallengeInstruction,
        pickChallengeInstruction,
        buildPrompt,
        classifyImages,
        cellRect,
        parseModelAnswer,
        answerToPoints,
        scoreAnswer,
    };
});

'use strict';

// 视觉识别客户端：三家 provider 全部走 OpenAI 兼容 chat/completions，单编码号拼图。
(function exposeCaptchaVision(root, factory) {
    const api = factory();
    if (typeof module === 'object' && module.exports) module.exports = api;
    root.XynigoCaptchaVision = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createVisionClient() {

    function chatCompletionsUrl(baseUrl) {
        const trimmed = String(baseUrl || '').trim().replace(/\/+$/, '');
        if (!trimmed) throw new Error('Base URL 未配置');
        if (/\/chat\/completions$/.test(trimmed)) return trimmed;
        return trimmed + '/chat/completions';
    }

    function buildChatBody(config, imageDataUrl, prompt) {
        if (!config.model) throw new Error('model 未配置');
        if (!config.apiKey) throw new Error('API Key 未配置');
        return {
            model: config.model,
            messages: [{
                role: 'user',
                content: [
                    { type: 'text', text: prompt },
                    { type: 'image_url', image_url: { url: imageDataUrl } },
                ],
            }],
            temperature: 0,
            max_tokens: 1024, // glm-4v-flash 上限 1024（越界报 1210）；答案只是一小段 JSON，足够。
            stream: false,
        };
    }

    function buildRequest(config, imageDataUrl, prompt) {
        return {
            url: chatCompletionsUrl(config.baseUrl),
            options: {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: 'Bearer ' + config.apiKey,
                },
                body: JSON.stringify(buildChatBody(config, imageDataUrl, prompt)),
            },
        };
    }

    // content 可能是字符串，也可能是分段数组；思考型模型可能把正文放 reasoning_content。
    function extractResponseText(json) {
        const message = json && json.choices && json.choices[0] && json.choices[0].message;
        if (!message) return '';
        if (typeof message.content === 'string' && message.content.trim()) return message.content;
        if (Array.isArray(message.content)) {
            const text = message.content
                .map((part) => (part && typeof part.text === 'string' ? part.text : ''))
                .join('');
            if (text.trim()) return text;
        }
        if (typeof message.reasoning_content === 'string' && message.reasoning_content.trim()) {
            return message.reasoning_content;
        }
        return '';
    }

    function stripDataUrlPrefix(dataUrl) {
        const commaIndex = String(dataUrl || '').indexOf(',');
        return commaIndex >= 0 ? String(dataUrl).slice(commaIndex + 1) : String(dataUrl || '');
    }

    function isImageRejection(status, bodyText) {
        if (status === 1210) return true;
        const text = String(bodyText || '');
        return /image|base64|图片/i.test(text) && !/quota|余额|欠费|api key|invalid/i.test(text);
    }

    // 发起识别调用。个别 provider 对 data:image 前缀不兼容：失败且疑似图片格式问题时，
    // 自动降级为裸 base64 重试一次。返回 {ok, status, text, latencyMs, error, retryUsed}。
    async function callVisionModel(config, imageDataUrl, prompt, fetchImpl) {
        const doFetch = fetchImpl || globalThis.fetch;
        if (typeof doFetch !== 'function') throw new Error('当前环境无 fetch 实现');

        async function attempt(payloadImage) {
            const request = buildRequest(config, payloadImage, prompt);
            const startedAt = Date.now();
            const response = await doFetch(request.url, request.options);
            const latencyMs = Date.now() - startedAt;
            let bodyText = '';
            try { bodyText = await response.text(); } catch (_error) { /* 空响应体 */ }
            let json = null;
            try { json = JSON.parse(bodyText); } catch (_error) { /* 非 JSON 响应 */ }
            return { response, latencyMs, bodyText, json };
        }

        let first;
        try {
            first = await attempt(imageDataUrl);
        } catch (error) {
            return { ok: false, status: 0, text: '', latencyMs: 0, error: '网络请求失败：' + error.message, retryUsed: false };
        }
        if (first.response.ok) {
            return { ok: true, status: first.response.status, text: extractResponseText(first.json), latencyMs: first.latencyMs, error: '', retryUsed: false };
        }
        if (isImageRejection(first.response.status, first.bodyText)) {
            try {
                const second = await attempt(stripDataUrlPrefix(imageDataUrl));
                if (second.response.ok) {
                    return { ok: true, status: second.response.status, text: extractResponseText(second.json), latencyMs: second.latencyMs, error: '', retryUsed: true };
                }
                return { ok: false, status: second.response.status, text: '', latencyMs: second.latencyMs, error: second.bodyText.slice(0, 300), retryUsed: true };
            } catch (error) {
                return { ok: false, status: 0, text: '', latencyMs: 0, error: '重试网络失败：' + error.message, retryUsed: true };
            }
        }
        return { ok: false, status: first.response.status, text: '', latencyMs: first.latencyMs, error: first.bodyText.slice(0, 300), retryUsed: false };
    }

    return { chatCompletionsUrl, buildChatBody, buildRequest, extractResponseText, stripDataUrlPrefix, isImageRejection, callVisionModel };
});

'use strict';

// 评测统计：解题日志聚合、双模型配对比较、样本回放评分。
(function exposeCaptchaStats(root, factory) {
    const api = factory();
    if (typeof module === 'object') module.exports = api;
    root.XynigoCaptchaStats = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createStats() {

    function appendTrim(list, record, cap) {
        const next = Array.isArray(list) ? list.slice() : [];
        next.push(record);
        while (next.length > cap) next.shift();
        return next;
    }

    function average(values) {
        if (!values.length) return null;
        const sum = values.reduce((acc, value) => acc + value, 0);
        return Math.round((sum / values.length) * 10) / 10;
    }

    // 按模型聚合：attempts / pass / fail / error / passRate / avgLatencyMs。
    // role=primary 的记录计入真实解题结果；role=shadow 只有与主模型的答案一致性可看。
    function aggregateSolves(records) {
        const groups = new Map();
        (records || []).forEach((record) => {
            if (!record || record.role !== 'primary') return;
            const key = (record.provider || '?') + '/' + (record.model || '?');
            if (!groups.has(key)) {
                groups.set(key, { model: key, attempts: 0, pass: 0, fail: 0, error: 0, latencies: [] });
            }
            const group = groups.get(key);
            group.attempts += 1;
            if (record.outcome === 'pass') { group.pass += 1; group.latencies.push(record.latencyMs || 0); }
            else if (record.outcome === 'fail') group.fail += 1;
            else group.error += 1;
        });
        const rows = Array.from(groups.values()).map((group) => ({
            model: group.model,
            attempts: group.attempts,
            pass: group.pass,
            fail: group.fail,
            error: group.error,
            passRate: group.attempts ? Math.round((group.pass / group.attempts) * 1000) / 10 : null,
            avgLatencyMs: average(group.latencies),
        }));
        rows.sort((a, b) => b.attempts - a.attempts);
        return rows;
    }

    // 配对比较：同一 puzzleId 下 primary 与 shadow 答案一致率。
    // primary 的通过率 = 真实过验率；shadow 只有"与主模型一致率"可看。
    function pairCompare(records) {
        const byPuzzle = new Map();
        (records || []).forEach((record) => {
            if (!record || !record.puzzleId) return;
            if (!byPuzzle.has(record.puzzleId)) byPuzzle.set(record.puzzleId, {});
            byPuzzle.get(record.puzzleId)[record.role] = record;
        });
        let pairs = 0;
        let agree = 0;
        let primaryPass = 0;
        let primaryCount = 0;
        byPuzzle.forEach((roles) => {
            if (!roles.primary || !roles.shadow) return;
            pairs += 1;
            const a = JSON.stringify(roles.primary.answer || []);
            const b = JSON.stringify(roles.shadow.answer || []);
            if (a === b) agree += 1;
            primaryCount += 1;
            if (roles.primary.outcome === 'pass') primaryPass += 1;
        });
        return {
            pairs,
            agree,
            disagree: pairs - agree,
            agreeRate: pairs ? Math.round((agree / pairs) * 1000) / 10 : null,
            primaryPassRate: primaryCount ? Math.round((primaryPass / primaryCount) * 1000) / 10 : null,
        };
    }

    // 回放评测汇总：samples=[{sample, result:{answer, latencyMs, ok}}]。
    function scoreReplay(entries) {
        const rows = (entries || []).map((entry) => {
            const scored = entry.result && entry.result.ok
                ? scoreAnswerSafe(entry.result.answer, entry.sample.groundTruth)
                : { exact: false, precision: 0, recall: 0 };
            return {
                sampleId: entry.sample.id,
                groundTruth: entry.sample.groundTruth || [],
                answer: entry.result && entry.result.answer ? entry.result.answer : [],
                ok: Boolean(entry.result && entry.result.ok),
                error: entry.result && entry.result.error ? entry.result.error : '',
                latencyMs: entry.result ? entry.result.latencyMs || 0 : 0,
                exact: scored.exact,
                precision: scored.precision,
                recall: scored.recall,
            };
        });
        const n = rows.length;
        const exactCount = rows.filter((row) => row.exact).length;
        return {
            n,
            exactCount,
            exactRate: n ? Math.round((exactCount / n) * 1000) / 10 : null,
            avgPrecision: n ? Math.round((rows.reduce((acc, row) => acc + row.precision, 0) / n) * 1000) / 10 : null,
            avgRecall: n ? Math.round((rows.reduce((acc, row) => acc + row.recall, 0) / n) * 1000) / 10 : null,
            avgLatencyMs: average(rows.filter((row) => row.ok).map((row) => row.latencyMs)),
            rows,
        };
    }

    let scoreAnswerImpl = null;
    function scoreAnswerSafe(answer, groundTruth) {
        if (scoreAnswerImpl) return scoreAnswerImpl(answer, groundTruth);
        // 独立使用本模块时的兜底实现（与 puzzle.scoreAnswer 等价）。
        const pred = new Set((answer || []).map(Number));
        const truth = new Set((groundTruth || []).map(Number));
        let hit = 0;
        truth.forEach((n) => { if (pred.has(n)) hit += 1; });
        return {
            exact: pred.size === truth.size && hit === truth.size,
            precision: pred.size ? hit / pred.size : 0,
            recall: truth.size ? hit / truth.size : 0,
        };
    }
    // 允许宿主（popup/background）注入 puzzle.scoreAnswer，避免重复实现漂移。
    function setScoreAnswer(impl) { scoreAnswerImpl = impl; }

    return { appendTrim, aggregateSolves, pairCompare, scoreReplay, setScoreAnswer };
});

'use strict';

// 解题编排：检测 → shadow DOM 取图 → 拼编号图 → 桥接识别 → 合成点击 → 等结果 → 刷新重试。
// 平台差异全部收进 bridge（扩展=background 中转；Tampermonkey=GM 直连），本文件只管 DOM 与流程。
// DOM 细节（分类阈值/行优先排序/pointer 全序列点击）承自 v0.2.0 实测实现。
(function exposeCaptchaAgent(root, factory) {
    const api = factory(root.XynigoCaptchaPuzzle);
    if (typeof module === 'object' && module.exports) module.exports = api;
    root.XynigoCaptchaAgent = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createCaptchaAgent(puzzle) {

    const CHALLENGE_TAG = 'nine-captcha-custom';
    const DIALOG_SELECTOR = '.si-verify-block-request-dialog'; // 组件改名/换结构时的兜底检测锚点。
    const INSTRUCTION_SELECTORS = [
        'h1', 'h2', 'h3', 'h4', '[role="heading"]',
        '[class*="title"]', '[class*="prompt"]', '[class*="tips"]', '[class*="tip"]', '[class*="desc"]',
    ].join(',');
    const REFRESH_SELECTOR = '.nine-refresh';
    const POLL_INTERVAL_MS = 2000;
    const OUTCOME_POLL_MS = 400;
    const CLICK_GAP_MIN_MS = 500;   // 相邻格子点击间隔下限，模拟人工节奏。
    const CLICK_GAP_MAX_MS = 1500;
    const REFRESH_SETTLE_MS = 2000; // 刷新验证码后等待新图渲染。
    const MAX_CELL_FETCH_FAILURES = 3; // 单轮允许拉取失败的格子图上限（URL 有过期机制）。

    function createAgent(bridge, env) {
        const cfg = env || {};
        const log = cfg.log || function () {};
        const warn = cfg.warn || function () {};
        const sleep = cfg.sleep || ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
        const randInt = cfg.randInt || ((min, max) => Math.floor(min + Math.random() * (max - min + 1)));
        const doc = cfg.document || document;
        const win = cfg.window || (typeof window !== 'undefined' ? window : undefined);

        let running = false;
        let timer = null;
        let observer = null;

        function searchFrames(selector) {
            const hits = [];
            const collect = (scope) => {
                try { scope.querySelectorAll(selector).forEach((element) => hits.push(element)); } catch (_error) { /* 跨域 iframe 不可访问。 */ }
            };
            collect(doc);
            try {
                for (const frame of doc.querySelectorAll('iframe')) collect(frame.contentDocument);
            } catch (_error) { /* iframe 枚举失败不影响主文档。 */ }
            return hits;
        }

        function captchaIsPresent() {
            return searchFrames(CHALLENGE_TAG).length > 0 || searchFrames(DIALOG_SELECTOR).length > 0;
        }

        function readVisibleText(element) {
            if (!element) return '';
            return String(element.innerText || element.textContent || '').trim();
        }

        // 规则文字通常在 nine-captcha-custom 外层 dialog 的 title/tip 节点，
        // 也有版本放进 open shadowRoot。收集候选后由 puzzle 纯函数筛出短规则文字。
        function extractChallengeInstruction(challengeRoot) {
            const candidates = [];
            const scopes = [];
            const dialog = challengeRoot.closest && challengeRoot.closest(DIALOG_SELECTOR);
            if (dialog) scopes.push(dialog);
            if (challengeRoot.shadowRoot) scopes.push(challengeRoot.shadowRoot);
            scopes.forEach((scope) => {
                try {
                    scope.querySelectorAll(INSTRUCTION_SELECTORS).forEach((element) => candidates.push(readVisibleText(element)));
                } catch (_error) { /* 单个选择器失效不影响整体兜底。 */ }
                candidates.push(readVisibleText(scope));
            });
            return puzzle.pickChallengeInstruction(candidates);
        }

        function extractChallenge() {
            for (const challengeRoot of searchFrames(CHALLENGE_TAG)) {
                const shadow = challengeRoot.shadowRoot;
                if (!shadow) continue;
                const imgs = Array.prototype.slice.call(shadow.querySelectorAll('img'));
                if (imgs.length < 10) continue;
                const metas = imgs.map((img) => {
                    const box = img.getBoundingClientRect();
                    return {
                        el: img,
                        src: img.currentSrc || img.src || '',
                        width: box.width || img.width || 0,
                        top: box.top,
                        left: box.left,
                    };
                });
                const classified = puzzle.classifyImages(metas);
                if (classified.ok) {
                    classified.root = challengeRoot;
                    classified.instruction = extractChallengeInstruction(challengeRoot);
                    return classified;
                }
            }
            return null;
        }

        function loadImage(src) {
            return new Promise((resolve, reject) => {
                const image = new (win ? win.Image : Image)();
                image.onload = () => resolve(image);
                image.onerror = () => reject(new Error('图片解码失败'));
                image.src = src;
            });
        }

        // 组装编号拼图：顶部「提示图」+ 3x3 红色编号格（1-9 行优先）；缺图画灰格容错。
        function composePuzzle(hintImage, cellImages) {
            const layout = puzzle.LAYOUT;
            const canvas = doc.createElement('canvas');
            canvas.width = layout.canvasWidth;
            canvas.height = layout.canvasHeight;
            const ctx = canvas.getContext('2d');
            if (!ctx) throw new Error('canvas 2d 上下文不可用');
            ctx.fillStyle = '#ffffff';
            ctx.fillRect(0, 0, canvas.width, canvas.height);

            ctx.fillStyle = '#333333';
            ctx.font = '14px sans-serif';
            ctx.textBaseline = 'top';
            ctx.fillText(layout.hintLabelText, layout.hintLabelPos.x, layout.hintLabelPos.y);
            ctx.fillText(layout.gridLabelText, layout.gridLabelPos.x, layout.gridLabelPos.y);

            if (hintImage) ctx.drawImage(hintImage, layout.hintRect.x, layout.hintRect.y, layout.hintRect.w, layout.hintRect.h);

            cellImages.forEach((image, index) => {
                const rect = puzzle.cellRect(index + 1);
                if (image) {
                    ctx.drawImage(image, rect.x, rect.y, rect.w, rect.h);
                } else {
                    ctx.fillStyle = '#dddddd';
                    ctx.fillRect(rect.x, rect.y, rect.w, rect.h);
                }
            });

            // 红色编号角标最后画，确保不被图片覆盖。
            const badge = layout.badgeSize;
            for (let index = 1; index <= 9; index += 1) {
                const rect = puzzle.cellRect(index);
                ctx.fillStyle = '#e02020';
                ctx.fillRect(rect.x, rect.y, badge, badge);
                ctx.fillStyle = '#ffffff';
                ctx.font = 'bold 18px sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillText(String(index), rect.x + badge / 2, rect.y + badge / 2 + 1);
                ctx.textAlign = 'start';
                ctx.textBaseline = 'alphabetic';
            }
            return canvas.toDataURL('image/jpeg', 0.9);
        }

        // 全序列 pointer+mouse 合成点击，行为对齐真实指针路径（真实环境验证过的写法）。
        function syntheticClick(element, clientX, clientY) {
            const options = {
                pointerType: 'mouse', cancelable: true, bubbles: true,
                view: win, clientX, clientY, button: 0, buttons: 1,
            };
            const Pointer = win ? win.PointerEvent : undefined;
            if (typeof Pointer === 'function') {
                for (const type of ['pointerover', 'pointerenter', 'pointermove']) {
                    element.dispatchEvent(new Pointer(type, options));
                }
                element.dispatchEvent(new Pointer('pointerdown', options));
            }
            for (const type of ['mouseover', 'mouseenter', 'mousemove']) {
                element.dispatchEvent(new MouseEvent(type, options));
            }
            element.dispatchEvent(new MouseEvent('mousedown', options));
            if (typeof Pointer === 'function') element.dispatchEvent(new Pointer('pointerup', options));
            element.dispatchEvent(new MouseEvent('mouseup', options));
            element.dispatchEvent(new MouseEvent('click', options));
        }

        function clickElementCenter(element) {
            const box = element.getBoundingClientRect();
            syntheticClick(element, box.x + box.width / 2, box.y + box.height / 2);
        }

        async function clickMatches(cells, matches) {
            for (const n of matches) {
                const target = cells[n - 1] && cells[n - 1].el;
                if (!target) continue;
                clickElementCenter(target);
                log('点击格子', n);
                await sleep(randInt(CLICK_GAP_MIN_MS, CLICK_GAP_MAX_MS));
            }
        }

        function waitGone(challengeRoot) {
            const deadline = Date.now() + (cfg.settleTimeoutMs || 8000);
            return new Promise((resolve) => {
                const poll = setInterval(() => {
                    if (!challengeRoot.isConnected || !doc.contains(challengeRoot)) {
                        clearInterval(poll);
                        resolve(true);
                        return;
                    }
                    if (Date.now() > deadline) {
                        clearInterval(poll);
                        resolve(false);
                    }
                }, cfg.outcomePollMs || OUTCOME_POLL_MS);
            });
        }

        async function clickRefresh(challenge) {
            const shadow = challenge && challenge.root && challenge.root.shadowRoot;
            const refresh = (shadow && shadow.querySelector(REFRESH_SELECTOR)) || doc.querySelector(REFRESH_SELECTOR);
            if (!refresh) {
                warn('未找到刷新按钮，等待组件自动换图。');
                return false;
            }
            clickElementCenter(refresh);
            await sleep(REFRESH_SETTLE_MS);
            return true;
        }

        function makeRecord(puzzleId, role, meta, extra) {
            return Object.assign({
                ts: Date.now(),
                puzzleId,
                role,
                provider: (meta && meta.provider) || '?',
                model: (meta && meta.model) || '?',
                latencyMs: 0,
                answer: [],
                outcome: 'error',
                error: '',
            }, extra || {});
        }

        // 取图：URL 有过期机制，取到立即逐张拉取；单图失败占位灰格，超限放弃本轮。
        async function fetchPuzzleSources(challenge) {
            const sources = [challenge.hint].concat(challenge.cells);
            const dataUrls = [];
            let cellFailures = 0;
            for (let index = 0; index < sources.length; index += 1) {
                try {
                    dataUrls.push(await bridge.fetchImage(sources[index].src));
                } catch (_error) {
                    dataUrls.push('');
                    if (index > 0) cellFailures += 1;
                }
            }
            if (!dataUrls[0]) throw new Error('提示图拉取失败');
            if (cellFailures > MAX_CELL_FETCH_FAILURES) throw new Error(`格子图拉取失败 ${cellFailures} 张（URL 可能已过期）`);
            const hintImage = await loadImage(dataUrls[0]);
            const cellImages = [];
            for (let index = 0; index < 9; index += 1) {
                cellImages.push(dataUrls[index + 1] ? await loadImage(dataUrls[index + 1]) : null);
            }
            return composePuzzle(hintImage, cellImages);
        }

        // 单次解题会话：最多 maxRounds 轮。每轮重新提取组件并取图——刷新换图后
        // 图片 URL 与 DOM 元素都会更换，必须用新一轮的拼图与元素解题/点击。
        async function solveSession() {
            const puzzleId = Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 6);

            const config = await bridge.getConfig();
            if (!config || !config.model || !config.apiKey) {
                if (!notConfiguredLogged) {
                    warn('模型未配置（缺 model 或 API Key）：请在扩展弹窗填写 API Key 并保存。');
                    notConfiguredLogged = true;
                }
                return;
            }

            for (let round = 1; round <= (config.maxRounds || 3); round += 1) {
                const challenge = extractChallenge();
                if (!challenge) {
                    warn('检测到验证码对话框，但未能解析出提示图+9 格子结构（组件可能已改版或在不可访问的 iframe 内）。');
                    return;
                }
                log(`第 ${round}/${config.maxRounds} 轮识别…`);
                const prompt = puzzle.buildPrompt(challenge.instruction);
                if (challenge.instruction) {
                    log('页面验证规则：', challenge.instruction);
                } else {
                    log('未提取到验证规则标题，本轮使用默认“与提示图同类”规则。');
                }

                let puzzleData;
                try {
                    puzzleData = await fetchPuzzleSources(challenge);
                } catch (error) {
                    warn('取图/拼图失败：', error && error.message);
                    return;
                }

                let solved;
                try {
                    solved = await bridge.solve(puzzleData, prompt);
                } catch (error) {
                    warn('识别桥接失败：', error && error.message);
                    return;
                }

                // 影子模型只记录答案不点击，供配对比较。
                if (solved.shadow) {
                    const shadowMeta = solved.compare || {};
                    let shadowAnswer = [];
                    if (solved.shadow.ok) {
                        try { shadowAnswer = puzzle.parseModelAnswer(solved.shadow.text).matches; } catch (_error) { /* 记空 */ }
                    }
                    await bridge.appendLogs([makeRecord(puzzleId, 'shadow', shadowMeta, {
                        latencyMs: solved.shadow.latencyMs || 0,
                        answer: shadowAnswer,
                        outcome: solved.shadow.ok ? 'pass' : 'error',
                        error: solved.shadow.error || '',
                    })]);
                }

                const primaryMeta = solved.config || {};
                if (!solved.primary || !solved.primary.ok) {
                    const primaryError = (solved.primary && solved.primary.error) || '识别调用失败';
                    await bridge.appendLogs([makeRecord(puzzleId, 'primary', primaryMeta, {
                        latencyMs: solved.primary ? solved.primary.latencyMs : 0,
                        outcome: 'error',
                        error: primaryError,
                    })]);
                    warn('识别调用失败：', primaryError);
                    if (/401/.test(primaryError)) {
                        warn('API Key 无效或欠费，请在扩展弹窗更新后重试。');
                        return;
                    }
                    return;
                }

                let matches;
                if (Array.isArray(solved.primary.answer)) {
                    matches = solved.primary.answer;
                } else {
                    try {
                        matches = puzzle.parseModelAnswer(solved.primary.text).matches;
                    } catch (_error) {
                        matches = [];
                    }
                }
                log('识别结果：', matches);

                if (!matches.length) {
                    await bridge.appendLogs([makeRecord(puzzleId, 'primary', primaryMeta, {
                        latencyMs: solved.primary.latencyMs,
                        outcome: 'fail',
                        error: '模型未返回有效编号：' + String(solved.primary.text || '').slice(0, 120),
                    })]);
                    if (!(await clickRefresh(challenge))) return;
                    continue;
                }

                await clickMatches(challenge.cells, matches);
                const passed = await waitGone(challenge.root);

                await bridge.appendLogs([makeRecord(puzzleId, 'primary', primaryMeta, {
                    latencyMs: solved.primary.latencyMs,
                    answer: matches,
                    outcome: passed ? 'pass' : 'fail',
                    error: passed ? '' : '点击后验证码未消失',
                })]);

                if (passed) {
                    log('验证码已通过，继续监听。');
                    if (config.collectSamples) {
                        try {
                            await bridge.appendSample({
                                id: puzzleId,
                                ts: Date.now(),
                                image: puzzleData,
                                instruction: challenge.instruction || '',
                                prompt,
                                groundTruth: matches,
                            });
                        } catch (_error) { /* 样本落盘失败不影响过验。 */ }
                    }
                    return;
                }
                warn(`第 ${round} 轮未过验，尝试刷新换图。`);
                if (round < config.maxRounds && !(await clickRefresh(challenge))) return;
            }
            warn('已达到最大重试次数，停止自动处理，请人工完成本次验证码。');
        }

        // 静默跳过是 2026-08-28 "验证码出现插件没反应"事故的根因之一：检测到验证码、
        // 自动解题关闭、配置读取失败三种状态都必须留下日志（每个验证码回合只提示一次）。
        let presenceLogged = false;
        let autoSolveOffLogged = false;
        let notConfiguredLogged = false;

        async function maybeSolve() {
            if (running) return;
            if (!captchaIsPresent()) {
                presenceLogged = false;
                autoSolveOffLogged = false;
                notConfiguredLogged = false;
                return;
            }
            if (!presenceLogged) {
                log('检测到验证码，开始处理。');
                presenceLogged = true;
            }
            let config;
            try {
                config = await bridge.getConfig();
            } catch (error) {
                warn('读取配置失败：', error && error.message);
                return;
            }
            if (config && config.autoSolve === false) {
                if (!autoSolveOffLogged) {
                    warn('「自动解题」已关闭：本次留人工处理，可在扩展弹窗勾选开启。');
                    autoSolveOffLogged = true;
                }
                return;
            }
            running = true;
            try {
                await solveSession();
            } finally {
                running = false;
            }
        }

        function start() {
            if (timer || observer) return;
            timer = setInterval(() => { maybeSolve().catch((error) => warn('轮询异常：', error && error.message)); }, POLL_INTERVAL_MS);
            if (typeof MutationObserver === 'function') {
                observer = new MutationObserver(() => { maybeSolve().catch(() => {}); });
                observer.observe(doc.documentElement, { childList: true, subtree: true });
            }
            log('已启动监听（nine-captcha-custom），验证码出现时自动处理。');
        }

        function stop() {
            if (timer) { clearInterval(timer); timer = null; }
            if (observer) { observer.disconnect(); observer = null; }
        }

        return { start, stop, maybeSolve };
    }

    return { createAgent };
});

globalThis.XynigoCaptchaUserscriptRuntime.install();

'use strict';

// 扩展端接线：chrome.runtime 桥接 background（取图/识别/落库），启动解题 agent。
(function bootCaptchaContent(root) {
    const agentFactory = root.XynigoCaptchaAgent;
    if (!agentFactory || typeof chrome === 'undefined' || !chrome.runtime) return;

    const isTopFrame = (() => {
        try { return typeof window !== 'undefined' && window.top === window; } catch (_error) { return true; }
    })();

    // 页内常驻状态卡：用 Shadow DOM 隔离 SHEIN 样式，让用户不开 DevTools 也能看到
    // “等待 / 配置异常 / 识别 / 点击 / 成功 / 失败”。all_frames 下仅顶层页显示，避免 iframe 重复。
    function createPageStatus() {
        if (!isTopFrame || typeof document === 'undefined') return { update() {} };

        const HOST_ID = 'xynigo-captcha-status-host';
        const version = (() => {
            try { return chrome.runtime.getManifest().version; } catch (_error) { return '?'; }
        })();
        let host = null;
        let card = null;
        let message = null;
        let toggle = null;
        let collapsed = false;

        function mount() {
            if (host && host.isConnected) return;
            if (!host) {
                host = document.createElement('div');
                host.id = HOST_ID;
                host.setAttribute('data-xynigo-owner', 'captcha-solver');
                host.setAttribute('style', [
                    'all:initial!important',
                    'position:fixed!important',
                    'right:16px!important',
                    'bottom:16px!important',
                    'z-index:2147483647!important',
                    'display:block!important',
                    'pointer-events:none!important',
                ].join(';'));
                const shadow = host.attachShadow({ mode: 'open' });
                const style = document.createElement('style');
                style.textContent = `
                    * { box-sizing: border-box; }
                    .card {
                        --accent: #0f766e;
                        width: min(320px, calc(100vw - 32px));
                        padding: 11px 12px;
                        border: 1px solid rgba(255,255,255,.18);
                        border-left: 4px solid var(--accent);
                        border-radius: 10px;
                        background: rgba(15, 23, 42, .94);
                        box-shadow: 0 10px 30px rgba(15, 23, 42, .28);
                        color: #f8fafc;
                        font: 13px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
                        pointer-events: auto;
                        backdrop-filter: blur(8px);
                    }
                    .card[data-kind="working"] { --accent: #3b82f6; }
                    .card[data-kind="success"] { --accent: #22c55e; }
                    .card[data-kind="warning"] { --accent: #f59e0b; }
                    .card[data-kind="error"] { --accent: #ef4444; }
                    .head { display: flex; align-items: center; gap: 8px; min-width: 0; }
                    .dot { width: 9px; height: 9px; flex: 0 0 9px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent) 25%, transparent); }
                    .title { flex: 1; min-width: 0; font-weight: 700; letter-spacing: .01em; }
                    .version { color: #94a3b8; font-size: 11px; font-weight: 500; }
                    .toggle { border: 0; padding: 0 2px; background: transparent; color: #cbd5e1; font: 700 16px/1 sans-serif; cursor: pointer; }
                    .message { margin-top: 6px; color: #e2e8f0; overflow-wrap: anywhere; }
                    .card.collapsed { width: auto; min-width: 158px; padding: 9px 10px; }
                    .card.collapsed .message, .card.collapsed .version { display: none; }
                `;
                card = document.createElement('div');
                card.className = 'card';
                card.dataset.kind = 'working';
                card.setAttribute('role', 'status');
                card.setAttribute('aria-live', 'polite');
                const head = document.createElement('div');
                head.className = 'head';
                const dot = document.createElement('span');
                dot.className = 'dot';
                const title = document.createElement('span');
                title.className = 'title';
                title.textContent = 'Xynigo 验证码插件';
                const versionNode = document.createElement('span');
                versionNode.className = 'version';
                versionNode.textContent = 'v' + version;
                toggle = document.createElement('button');
                toggle.className = 'toggle';
                toggle.type = 'button';
                toggle.textContent = '−';
                toggle.setAttribute('aria-label', '收起验证码插件状态');
                toggle.addEventListener('click', () => {
                    collapsed = !collapsed;
                    card.classList.toggle('collapsed', collapsed);
                    toggle.textContent = collapsed ? '+' : '−';
                    toggle.setAttribute('aria-label', collapsed ? '展开验证码插件状态' : '收起验证码插件状态');
                });
                message = document.createElement('div');
                message.className = 'message';
                message.textContent = '插件正在初始化…';
                head.append(dot, title, versionNode, toggle);
                card.append(head, message);
                shadow.append(style, card);
            }
            (document.documentElement || document.body).appendChild(host);
        }

        function printable(value) {
            if (typeof value === 'string') return value;
            try { return JSON.stringify(value); } catch (_error) { return String(value); }
        }

        function update(kind, ...parts) {
            mount();
            const nextKind = ['ready', 'working', 'success', 'warning', 'error'].includes(kind) ? kind : 'ready';
            card.dataset.kind = nextKind;
            host.setAttribute('data-status', nextKind);
            message.textContent = parts.map(printable).filter(Boolean).join(' ').slice(0, 240) || '等待验证码…';
        }

        mount();
        return { update };
    }

    const pageStatus = createPageStatus();
    pageStatus.update('working', '插件正在初始化…');

    function statusKind(parts, warning) {
        const text = parts.map((part) => typeof part === 'string' ? part : JSON.stringify(part)).join(' ');
        if (/已通过/.test(text)) return 'success';
        if (warning) return /失败|错误|无效|未配置|未找到|停止|超时/.test(text) ? 'error' : 'warning';
        if (/检测到|开始处理|识别|点击|迁移/.test(text)) return 'working';
        return 'ready';
    }

    const pageLog = (...args) => {
        pageStatus.update(statusKind(args, false), ...args);
        console.log('[XynigoCaptchaSolver]', ...args);
    };
    const pageWarn = (...args) => {
        pageStatus.update(statusKind(args, true), ...args);
        console.warn('[XynigoCaptchaSolver]', ...args);
    };

    function sendMessage(message) {
        return new Promise((resolve, reject) => {
            chrome.runtime.sendMessage(message, (response) => {
                if (chrome.runtime.lastError) {
                    reject(new Error(chrome.runtime.lastError.message));
                    return;
                }
                if (!response || response.ok === false) {
                    reject(new Error((response && response.error) || 'background 响应异常'));
                    return;
                }
                resolve(response);
            });
        });
    }

    const bridge = {
        getConfig: async () => {
            const response = await sendMessage({ type: 'captchaGetConfig' });
            return response.config;
        },
        fetchImage: async (url) => {
            const response = await sendMessage({ type: 'captchaFetchImage', url });
            return response.dataUrl;
        },
        solve: async (image, prompt) => await sendMessage({ type: 'captchaSolve', image, prompt }),
        appendLogs: async (records) => { await sendMessage({ type: 'captchaAppendLogs', records }); },
        appendSample: async (sample) => { await sendMessage({ type: 'captchaAppendSample', sample }); },
    };

    function showConfigStatus(config) {
        if (!config || !config.apiKey) {
            pageStatus.update('error', 'API Key 未配置：请在插件弹窗保存识别模型配置。');
        } else if (config.autoSolve === false) {
            pageStatus.update('warning', '自动解题已关闭：检测到验证码时将交给人工处理。');
        } else {
            pageStatus.update('ready', '自动解题已开启，正在等待验证码。');
        }
    }

    // popup 保存配置后立即同步页面卡；Tampermonkey shim 无 storage.onChanged 时自动跳过。
    if (chrome.storage && chrome.storage.onChanged && typeof chrome.storage.onChanged.addListener === 'function') {
        chrome.storage.onChanged.addListener((changes, areaName) => {
            if (areaName !== 'local' || !changes.xynigoCaptchaConfig) return;
            bridge.getConfig().then(showConfigStatus).catch((error) => {
                pageStatus.update('error', '更新页面配置状态失败：' + String((error && error.message) || error));
            });
        });
    }

    const agent = agentFactory.createAgent(bridge, {
        log: pageLog,
        warn: pageWarn,
    });

    // v0.2.0 曾把 API Key 存在站点 localStorage（xynigoCaptchaGlmKey），v0.3.x 配置在
    // chrome.storage。新配置缺 key 时自动迁移并开启自动解题，避免人工重填。
    async function migrateLegacyConfig() {
        try {
            const config = await bridge.getConfig();
            if (config && config.apiKey) return;
            const legacy = (typeof localStorage !== 'undefined' && localStorage.getItem('xynigoCaptchaGlmKey')) || '';
            if (!legacy) return;
            await sendMessage({
                type: 'captchaSaveConfig',
                config: Object.assign({}, config, { apiKey: legacy, autoSolve: true }),
            });
            pageLog('已从 v0.2.0 localStorage 迁移 API Key，并开启自动解题。');
        } catch (error) {
            pageWarn('旧版配置迁移失败：', error && error.message);
        }
    }

    async function startAgent() {
        await migrateLegacyConfig();
        agent.start();
        try {
            const config = await bridge.getConfig();
            showConfigStatus(config);
        } catch (error) {
            pageStatus.update('error', '读取插件配置失败：' + String((error && error.message) || error));
        }
    }

    startAgent().catch((error) => {
        pageWarn('插件启动失败：', error && error.message);
        agent.start();
    });
})(typeof globalThis !== 'undefined' ? globalThis : this);
